[package]
name = "ascendancy-server"
version = "0.1.0"
edition = "2024"


[dependencies]
ascendancy-shared = { path = "../shared"}
bevy = {workspace = true}
bevy_renet = {workspace = true}
bincode = {workspace = true}